
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    name: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  typeAliasesPackage: com.system.entity
  mapperLocations: classpath:mybatis/mapper/*.xml